# Generated by Django 4.2.11 on 2025-06-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
